---
- name: install pgbouncer
  apt: name=pgbouncer state=latest

- name: put pgbouncer config
  template: src=pgbouncer.ini dest=/etc/pgbouncer/pgbouncer.ini owner=postgres mode=0640 group=postgres
  notify: reload pgbouncer

- name: put pgbouncer defaults
  template: src=pgbouncer dest=/etc/default/pgbouncer

- name: start PGBouncer service
  service: name=pgbouncer state=started enabled=yes
